### ISSUE TITLE
 session.get no longer working? New API?

### ISSUE THREAD

**Issue by PescheHelfer** [de3sw2aq1/wattpad-ebook-scraper#16]
I haven't tried for quite some time and it worked before. But now, I get the following error:

```
  File ...\scrape.py", line 47, in download_story
    story_title = storyinfo['title']
KeyError: 'title'
```

Line 47 contains the following call:
`story_title = storyinfo['title']`

It seems storyinfo is empty. Calling it results in the following error:
`{'error_code': 1001, 'error_type': 'InvalidEndpoint', 'message': 'API method not found'}`

-> I suspect the API has changed. Is there any chance we can get it working under the new API?

Best regards
- spitfire

**Comment by de3sw2aq1** [comment]
It looks like it still works, I can check with a specific story if you can give me the link.

I'm not really maintaining this project at the moment. Most of the functionality got added to https://github.com/JimmXinu/FanFicFare though, you can try it. FanFicFare is usable on the command line or as a Calibre plugin

**Comment by PescheHelfer** [comment]
Thx very much, must have something to do with my local installation, then. I tried FanFicFare and it works perfectly, thx for pointing me to it! Best regards, Pesche
