### ISSUE TITLE
genshi dependency - thank you

### ISSUE THREAD

**Issue by cpina** [de3sw2aq1/wattpad-ebook-scraper#2]
Hi!

Opening this issue almost only to say THANK YOU!!! I really wanted it :-) and here it is.

Also, I had to install to genshi - perhaps mention in the README.md as well?

**Comment by de3sw2aq1** [comment]
You're welcome! Also, I fixed a bug in this just yesterday, so you found it at the perfect time.

I'll look at adding a proper `requirements.txt` or a real `setup.py`. That should include the genshi dependency.

Also, epubbuilder is really quite broken regarding Unicode characters. If I switch to something else I'll drop the genshi dependency.

**Comment by cpina** [comment]
I've added a quick note on my blog - http://pintant.cat/2015/07/02/wattpad-story-scraper/ mentioning this. Might be useful to other people... I spent some time before finding it.
