### ISSUE TITLE
does it no longer work?

### ISSUE THREAD

**Issue by spitfireCH** [de3sw2aq1/wattpad-ebook-scraper#7]
Does the original version still work for you? I tried both, the original and my modified version, but both produced the following error:

Traceback (most recent call last):
  File "scrape.py", line 34, in <module>
    categories = json.loads(session.get(API_GETCATEGORIES).content.decode('utf-8
'))
  File "E:\ProgramsW7\IT\Python34\lib\json\__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "E:\ProgramsW7\IT\Python34\lib\json\decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "E:\ProgramsW7\IT\Python34\lib\json\decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)

Is it possible Wattpad changed somehow?

**Comment by spitfireCH** [comment]
Looking bad, it seems Wattpad has blocked access. 

session.get(API_GETCATEGORIES).content results in the following:
b'<html>\r\n<head><title>403 Forbidden</title></head>\r\n<body bgcolor="white">\r\n<center><h1>403 Forbidden</h1></center>\r\n<hr><center>nginx</center>\r\n</body>\r\n</html>\r\n'

Whereas it used to produce categories before:
b'{"4":"Romance","5":"Science Fiction","3":"Fantasy","8":"Mystery\\/Suspense","7":"Humor","12":"Paranormal","9":"Horror","11":"Adventure","15":"Thriller","23":"Historical Fiction","1":"Teen Fiction","6":"Fan Fiction","2":"Poetry","17":"Short Story","21":"Non-Teen Fiction","14":"Action","18":"Vampire","22":"Werewolf","13":"Spiritual","16":"Non-Fiction","10":"Classics","20":"Watty Awards 2011","19":"Other"}'

Any idea how we can get around that?
If you open the webpages manually, they still work. Would it be possible to download them manually and then import the downloaded files?
Would it be possible to access them in a different way?
Thanks for any feedback!

**Comment by de3sw2aq1** [comment]
Lovely, they're blocking any user agent that contains "Python":

    $ curl -A 'Python' https://www.wattpad.com/apiv2/getcategories
    <html>
    <head><title>403 Forbidden</title></head>
    <body bgcolor="white">
    <center><h1>403 Forbidden</h1></center>
    <hr><center>nginx</center>
    </body>
    </html>

Lets just send and empty user agent header for now. (Or not send one, I haven't checked how requests is actually doing this.) This fixes it and this project works again.

If they keep this up, it will be quite unpleasant to fight them. They might have started blocking user agents with "python" for unrelated reasons though. We'll see.

**Comment by spitfireCH** [comment]
Excellent, thanks a lot for the quick fix!

According to their API documentation one needs to authorize, now. May this be part of the problem (or a future solution)?

https://developer.wattpad.com/docs/api#!/categories/GetCategories
https://developer.wattpad.com/docs/signin

**Comment by de3sw2aq1** [comment]
We're not actually using any of their official APIs. The documentation you linked is the new official, documented, v4 API. It doesn't actually provide any method to get the text of a story.

Instead we're using undocumented APIs (both apiv2 and v3) used by various things like Wattpad's Android app or their website. These unofficial APIs allow getting full stories (it's how the Android app loads them), but they don't officially want you to use them. We're using it anyway and it works (until they break it).

**Comment by spitfireCH** [comment]
I see, thanks for clarifying that. So, let's hope they don't break it any time soon!

**Comment by princenuce** [comment]
You can refer to this page: [doc truyen](http://doc-truyen.vaoday.net)

**Comment by vevev** [comment]
You can refer to this page: [doc truyen](http://doc-truyen.vaoday.net)
