### ISSUE TITLE
beautifier for epub

### ISSUE THREAD

**Issue by strider2000** [de3sw2aq1/wattpad-ebook-scraper#9]
Added smartypants.py to scrape.py directory, 
and edited scrape.py:
* add "import smartypants"
* change "chapter_html = chapter_req.content" to "chapter_html = smartypants.smartypants(chapter_req.content)"

best regards,

*** OLD/wattpad-ebook-scraper-master/scrape.py	2015-11-11 01:18:34.000000000 +0100
--- NEW/wattpad-ebook-scraper-master/scrape.py	2015-11-11 12:48:50.688431057 +0100
***************
*** 7,12 ****
--- 7,13 ----
  import dateutil.parser
  from genshi.input import HTML
  
+ import smartypants
  import ez_epub
  
  # Setup session to not hit Android download app page
***************
*** 80,86 ****
          print('Downloading "{chapter_title}": {chapter_id}'.format(chapter_title=chapter_title, chapter_id=chapter_id))
  
          chapter_req = session.get(API_STORYTEXT, params={'id': chapter_id})
!         chapter_html = chapter_req.content
  
  
          section = ez_epub.Section()
--- 81,87 ----
          print('Downloading "{chapter_title}": {chapter_id}'.format(chapter_title=chapter_title, chapter_id=chapter_id))
  
          chapter_req = session.get(API_STORYTEXT, params={'id': chapter_id})
!         chapter_html = smartypants.smartypants(chapter_req.content)
  
  
          section = ez_epub.Section()

**Comment by de3sw2aq1** [comment]
I personally usually convert the epub to mobi with Calibre, and it can do smart quotes conversion then. But this seems like a reasonable enough feature to add to the scraper. I'll add it.

**Comment by de3sw2aq1** [comment]
Implemented in bae5825844bcdad0bfb4f0c2f1d49620a1e58b11
